"""changed column

Revision ID: 9988fbc21eff
Revises: 25e27c2b4d78
Create Date: 2025-08-12 14:08:53.144676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9988fbc21eff'
down_revision: Union[str, Sequence[str], None] = '25e27c2b4d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
